# Generated by Django 3.2.18 on 2023-05-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_num', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=300)),
                ('release_date', models.DateField(blank=True, default=None, null=True)),
                ('popularity', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('backdrop_path', models.CharField(max_length=300)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
